services:
  api:
    container_name: go-api
    depends_on:
      - db
    build:  ./backend
    ports:
      - 8080:8080
    volumes:
      - .env:/app/.env
      - ./backend/services/admin_service/templates/password_reset_email.html:/app/password_reset_email.html
  db:
    container_name: go-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:  
      - coin-price:/data/db

volumes:
  coin-price: